---

fonts_path: fonts/
theme_path: scripts/custom_theme.R

rnaseq:
    fdr: 0.1
    high-affinity: ../rnaseq/diff_exp/verified_genes_plus_Venus/high-affinity-ZF-v-reporter-only/libsizenorm/high-affinity-ZF-v-reporter-only_rnaseq-libsizenorm-verified_genes_plus_Venus-diffexp-results-all.tsv
    low-affinity: ../rnaseq/diff_exp/verified_genes_plus_Venus/low-affinity-ZF-v-reporter-only/libsizenorm/low-affinity-ZF-v-reporter-only_rnaseq-libsizenorm-verified_genes_plus_Venus-diffexp-results-all.tsv
    low-affinity-w-clamp: ../rnaseq/diff_exp/verified_genes_plus_Venus/low-affinity-ZF-with-clamp-v-reporter-only/libsizenorm/low-affinity-ZF-with-clamp-v-reporter-only_rnaseq-libsizenorm-verified_genes_plus_Venus-diffexp-results-all.tsv

chipseq_coverage:
    chipseq-3:
        coverage: ../chipseq-3/datavis/affinity-dependent-peaks/libsizenorm/affinity-dependent-peaks-allsamples-allannotations-ZF-chipseq-libsizenorm-protection.tsv.gz
        peak_annotation: ../chipseq-3/datavis/affinity-dependent-peaks/libsizenorm/all-v-all/passing/ratio/peaks_cluster-1.bed
        transcripts: ../genome/annotations/Scer_transcripts_w_verifiedORFs-withVenus-URA3_reporter_strain.bed
        orfs: ../genome/annotations/Scer_nondubious_ORFs-withVenus-URA3_reporter_strain.bed
    chipseq-5-withVP16:
        coverage: ../chipseq-5/datavis/affinity-dependent-peaks/spikenorm/affinity-dependent-peaks-allsamples-allannotations-ZF-chipseq-spikenorm-protection.tsv.gz
        peak_annotation: ../chipseq-5/datavis/affinity-dependent-peaks/spikenorm/all-v-all/passing/protection/peaks_cluster-1.bed
        transcripts: ../genome/annotations/Scer_transcripts_w_verifiedORFs-withVenus-URA3_reporter_strain.bed
        orfs: ../genome/annotations/Scer_nondubious_ORFs-withVenus-URA3_reporter_strain.bed
    chipseq-5-noVP16:
        coverage: ../chipseq-5/datavis/affinity-dependent-peaks-noVP16/spikenorm/affinity-dependent-peaks-noVP16-allsamples-allannotations-ZF-chipseq-spikenorm-protection.tsv.gz
        peak_annotation: ../chipseq-5/datavis/affinity-dependent-peaks-noVP16/spikenorm/all-v-all/passing/protection/peaks_cluster-1.bed
        transcripts: ../genome/annotations/Scer_transcripts_w_verifiedORFs-withVenus-URA3_reporter_strain.bed
        orfs: ../genome/annotations/Scer_nondubious_ORFs-withVenus-URA3_reporter_strain.bed

chipseq_coverage_ratio:
    chipseq-5-withVP16:
        coverage: ../chipseq-5/datavis/affinity-dependent-peaks-filtered/spikenorm/affinity-dependent-peaks-filtered-allsamples-allannotations-ZF-chipseq-spikenorm-ratio.tsv.gz
        peak_annotation: ../chipseq-5/datavis/affinity-dependent-peaks-filtered/spikenorm/all-v-all/passing/ratio/peaks_cluster-1.bed
        transcripts: ../genome/annotations/Scer_transcripts_w_verifiedORFs-withVenus-URA3_reporter_strain.bed
        orfs: ../genome/annotations/Scer_nondubious_ORFs-withVenus-URA3_reporter_strain.bed
        motifs: ../zf_motif_enrichment/motifs/allmotifs.bed
        filter_groups:
            - high-affinity-ZF
            - low-affinity-ZF
            - low-affinity-ZF-with-clamp
    chipseq-5-noVP16:
        coverage: ../chipseq-5/datavis/affinity-dependent-peaks-filtered/spikenorm/affinity-dependent-peaks-filtered-allsamples-allannotations-ZF-chipseq-spikenorm-ratio.tsv.gz
        peak_annotation: ../chipseq-5/datavis/affinity-dependent-peaks-filtered/spikenorm/all-v-all/passing/ratio/peaks_cluster-1.bed
        transcripts: ../genome/annotations/Scer_transcripts_w_verifiedORFs-withVenus-URA3_reporter_strain.bed
        orfs: ../genome/annotations/Scer_nondubious_ORFs-withVenus-URA3_reporter_strain.bed
        motifs: ../zf_motif_enrichment/motifs/allmotifs.bed
        filter_groups:
            - high-affinity-ZF-noVP16
            - low-affinity-ZF-noVP16
            - low-affinity-ZF-with-clamp-noVP16

zf_venus_reporter_datavis:
    target_annotation: ../zf_data_integration/browser-shots/Venus/Venus.bed
    transcript_annotation: ../genome/annotations/Scer_transcripts_w_verifiedORFs-withVenus-URA3_reporter_strain.bed
    orf_annotation: ../genome/annotations/Scer_nondubious_ORFs-withVenus-URA3_reporter_strain.bed
    motif_annotation: ../genome/annotations/42-10_9bp_fimo_7e4.bed
    data: ../zf_data_integration/browser-shots/Venus/Venus_all-assays.tsv.gz

rnaseq_summary:
    rnaseq_fdr: 0.1
    motif_results: ../zf_motif_enrichment/comparisons/high-affinity-upregulated-transcripts-v-all-transcripts/high-affinity-upregulated-transcripts-v-all-transcripts_control_unmergedFIMOresults.tsv.gz
    high-affinity: ../rnaseq/diff_exp/verified_genes_plus_Venus/high-affinity-ZF-v-reporter-only/libsizenorm/high-affinity-ZF-v-reporter-only_rnaseq-libsizenorm-verified_genes_plus_Venus-diffexp-results-all.tsv
    low-affinity: ../rnaseq/diff_exp/verified_genes_plus_Venus/low-affinity-ZF-v-reporter-only/libsizenorm/low-affinity-ZF-v-reporter-only_rnaseq-libsizenorm-verified_genes_plus_Venus-diffexp-results-all.tsv
    low-affinity-w-clamp: ../rnaseq/diff_exp/verified_genes_plus_Venus/low-affinity-ZF-with-clamp-v-reporter-only/libsizenorm/low-affinity-ZF-with-clamp-v-reporter-only_rnaseq-libsizenorm-verified_genes_plus_Venus-diffexp-results-all.tsv

zf_chipseq_global_coverage:
    data: ../chipseq-3/qual_ctrl/scatter_plots/ZF_chipseq_union-bedgraph-libsizenorm-midpoint-window-500-allsamples.tsv.gz

expression_vs_chip_enrichment:
    high_rna: ../rnaseq/diff_exp/verified_genes_plus_Venus/high-affinity-ZF-v-reporter-only/libsizenorm/high-affinity-ZF-v-reporter-only_rnaseq-libsizenorm-verified_genes_plus_Venus-diffexp-results-all.tsv
    high_chip: ../chipseq-3/diff_binding/verified_genes_plus_Venus/high-affinity-ZF-v-reporter-only/libsizenorm/high-affinity-ZF-v-reporter-only_ZF-chipseq-libsizenorm-verified_genes_plus_Venus-diffbind-results-all.tsv
    low_rna: ../rnaseq/diff_exp/verified_genes_plus_Venus/low-affinity-ZF-v-reporter-only/libsizenorm/low-affinity-ZF-v-reporter-only_rnaseq-libsizenorm-verified_genes_plus_Venus-diffexp-results-all.tsv
    low_chip: ../chipseq-3/diff_binding/verified_genes_plus_Venus/low-affinity-ZF-v-reporter-only/libsizenorm/low-affinity-ZF-v-reporter-only_ZF-chipseq-libsizenorm-verified_genes_plus_Venus-diffbind-results-all.tsv
    clamp_rna: ../rnaseq/diff_exp/verified_genes_plus_Venus/low-affinity-ZF-with-clamp-v-reporter-only/libsizenorm/low-affinity-ZF-with-clamp-v-reporter-only_rnaseq-libsizenorm-verified_genes_plus_Venus-diffexp-results-all.tsv
    clamp_chip: ../chipseq-3/diff_binding/verified_genes_plus_Venus/low-affinity-ZF-with-clamp-v-reporter-only/libsizenorm/low-affinity-ZF-with-clamp-v-reporter-only_ZF-chipseq-libsizenorm-verified_genes_plus_Venus-diffbind-results-all.tsv

motif_distance_vs_rnaseq:
    rnaseq: ../rnaseq/diff_exp/verified_genes_plus_Venus/high-affinity-ZF-v-reporter-only/libsizenorm/high-affinity-ZF-v-reporter-only_rnaseq-libsizenorm-verified_genes_plus_Venus-diffexp-results-all.tsv
    motifs: ../zf_motif_enrichment/comparisons/high-affinity-upregulated-transcripts-v-all-transcripts/high-affinity-upregulated-transcripts-v-all-transcripts_control_unmergedFIMOresults.tsv.gz

rna_vs_chip_windows:
    rna: ../rnaseq/diff_exp/verified_genes_plus_Venus/high-affinity-ZF-v-reporter-only/libsizenorm/high-affinity-ZF-v-reporter-only_rnaseq-libsizenorm-verified_genes_plus_Venus-diffexp-results-all.tsv
    chip: ../chipseq-3/diff_binding/verified_genes_plus_Venus_upstream_windows/high-affinity-ZF-v-reporter-only/libsizenorm/high-affinity-ZF-v-reporter-only_ZF-chipseq-libsizenorm-verified_genes_plus_Venus_upstream_windows-diffbind-results-all.tsv

chipseq_global_abundance:
    chipseq-4-qc: ../chipseq-4/qual_ctrl/spikein/ZF-chipseq_spikein-counts.tsv
    chipseq-5: ../chipseq-5/qual_ctrl/spikein/ZF-chipseq_spikein-counts.tsv

reporter_chipseq_qc:
    chipseq-3: ../chipseq-3/datavis/reporter-binding-site/libsizenorm/reporter-binding-site-allsamples-allannotations-ZF-chipseq-libsizenorm-protection.tsv.gz
    chipseq-4-qc: ../chipseq-4/datavis/reporter-binding-site/spikenorm/reporter-binding-site-allsamples-allannotations-ZF-chipseq-spikenorm-protection.tsv.gz
    chipseq-5: ../chipseq-5/datavis/reporter-binding-site/spikenorm/reporter-binding-site-allsamples-allannotations-ZF-chipseq-spikenorm-protection.tsv.gz

rnaseq_summary_mutants:
    high_affinity_zev_mutant: ../rnaseq/diff_exp/verified_genes_plus_Venus/high-affinity-ZF-ZEV-mutant-v-reporter-only/libsizenorm/high-affinity-ZF-ZEV-mutant-v-reporter-only_rnaseq-libsizenorm-verified_genes_plus_Venus-diffexp-results-all.tsv
    high_affinity_zftf_mutant: ../rnaseq/diff_exp/verified_genes_plus_Venus/high-affinity-ZF-ZFTF-mutant-v-reporter-only/libsizenorm/high-affinity-ZF-ZFTF-mutant-v-reporter-only_rnaseq-libsizenorm-verified_genes_plus_Venus-diffexp-results-all.tsv

chip_hits_w_rnaseq_info:
    affinity_dependent_peaks: ../chipseq-5/diff_binding/ZF-cumulative-peaklist-spikenorm/low-affinity-ZF-v-high-affinity-ZF/libsizenorm/low-affinity-ZF-v-high-affinity-ZF_ZF-chipseq-libsizenorm-ZF-cumulative-peaklist-spikenorm-diffbind-results-down.tsv
    chip_results:
        high: ../chipseq-5/diff_binding/ZF-cumulative-peaklist-spikenorm/high-affinity-ZF-v-reporter-only/spikenorm/high-affinity-ZF-v-reporter-only_ZF-chipseq-spikenorm-ZF-cumulative-peaklist-spikenorm-diffbind-results-all.tsv
        low: ../chipseq-5/diff_binding/ZF-cumulative-peaklist-spikenorm/low-affinity-ZF-v-reporter-only/spikenorm/low-affinity-ZF-v-reporter-only_ZF-chipseq-spikenorm-ZF-cumulative-peaklist-spikenorm-diffbind-results-all.tsv
        low_clamp: ../chipseq-5/diff_binding/ZF-cumulative-peaklist-spikenorm/low-affinity-ZF-with-clamp-v-reporter-only/spikenorm/low-affinity-ZF-with-clamp-v-reporter-only_ZF-chipseq-spikenorm-ZF-cumulative-peaklist-spikenorm-diffbind-results-all.tsv
    rna_results:
        high: ../rnaseq/diff_exp/verified_genes_plus_Venus/high-affinity-ZF-v-reporter-only/libsizenorm/high-affinity-ZF-v-reporter-only_rnaseq-libsizenorm-verified_genes_plus_Venus-diffexp-results-all.tsv
        low: ../rnaseq/diff_exp/verified_genes_plus_Venus/low-affinity-ZF-v-reporter-only/libsizenorm/low-affinity-ZF-v-reporter-only_rnaseq-libsizenorm-verified_genes_plus_Venus-diffexp-results-all.tsv
        low_clamp: ../rnaseq/diff_exp/verified_genes_plus_Venus/low-affinity-ZF-with-clamp-v-reporter-only/libsizenorm/low-affinity-ZF-with-clamp-v-reporter-only_rnaseq-libsizenorm-verified_genes_plus_Venus-diffexp-results-all.tsv


rnaseq_volcano_custom:
    low_v_high: ../rnaseq/diff_exp/verified_genes_plus_Venus/low-affinity-ZF-v-high-affinity-ZF/libsizenorm/low-affinity-ZF-v-high-affinity-ZF_rnaseq-libsizenorm-verified_genes_plus_Venus-diffexp-results-all.tsv
    low_clamp_v_high: ../rnaseq/diff_exp/verified_genes_plus_Venus/low-affinity-ZF-with-clamp-v-high-affinity-ZF/libsizenorm/low-affinity-ZF-with-clamp-v-high-affinity-ZF_rnaseq-libsizenorm-verified_genes_plus_Venus-diffexp-results-all.tsv
    low_clamp_v_low: ../rnaseq/diff_exp/verified_genes_plus_Venus/low-affinity-ZF-with-clamp-v-low-affinity-ZF/libsizenorm/low-affinity-ZF-with-clamp-v-low-affinity-ZF_rnaseq-libsizenorm-verified_genes_plus_Venus-diffexp-results-all.tsv
